### ISSUE TITLE
Setting --semi_percent=1 cause error

### ISSUE THREAD

**Issue by NUS-Tim** [FengheTan9/Multi-Level-Global-Context-Cross-Consistency#4]
assert len(self.secondary_indices) >= self.secondary_batch_size > 0
AssertionError

**Comment by FengheTan9** [comment]
Thanks for using our code.
`TwoStreamBatchSampler(primary_indices, secondary_indices, batch_size, secondary_batch_size)`
The TwoStreamBatchSampler function divides the total batch into labeled batch (batch_size - secondary_batch_size), and unlabeled batch (secondary_batch_size). In addition, primary_indices is a set of labeled sample divisions, and secondary_indices is a set of unlabel sample divisions.
The above error shows that the unlabeled sample divisions set is smaller than the unlabeled batch.

**Comment by NUS-Tim** [comment]
Thanks for the clarification. So basically the code currently does not support the fully-supervised case or did I miss anything?

**Comment by FengheTan9** [comment]
You can follow our fully-supervised  [benchmarks](https://github.com/FengheTan9/Medical_Image_Segmentation_Benchmark).
