### ISSUE TITLE
about test model

### ISSUE THREAD

**Issue by Minami77** [FengheTan9/Multi-Level-Global-Context-Cross-Consistency#6]
Hi
Thanks for sharing!

I found the test model(UNet) you used contians ConvMixer layer in your paper. But in the Evaluation Metrics and Comparison Methods section of your paper, you mentioned "all methods utilize U-Net as the backbone".  Does this mean the UNet for all comparison methods contians ConvMixer layer?

**Comment by FengheTan9** [comment]
Thanks for using our code.
All methods use U-Net for backbones, including encoders and decoders with skip-connections. And the ConvMixer module is a part of our proposed method (ie. MGCC), and the backbones (ie. U-Net) of other methods do not include ConvMixer.

**Comment by Minami77** [comment]
Thanks for your response.
If comparison methods do not contain ConvMixer, isn't it fair to conduct the comparison experiment in this way?

**Comment by FengheTan9** [comment]
Well, ConvMixer is part of our SSL strategy for extract multi-level global context. This is unique to our SSL method. And our strategy can be used on any encoder-decoder structure.

**Comment by Minami77** [comment]
Thanks for your response！
